# Generated by Django 4.1.7 on 2023-03-10 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='tittle',
            new_name='title',
        ),
    ]
