# Generated by Django 4.1.7 on 2023-03-10 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_tittle_taskmodel_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskmodel',
            options={},
        ),
        migrations.AlterOrderWithRespectTo(
            name='taskmodel',
            order_with_respect_to='user',
        ),
    ]
